Repository ut-issl/s2e-documents, pull requests merged in 2022-03, with the labels that each got.

#18 Add I2c HILS test tutorial
  README.md
  SUMMARY.md
  Tutorials/HowToPerformI2cHilsTest.md
  Tutorials/HowToPerformUartHilsTest.md
  Tutorials/figs/SerialPortCommunication_Confirmation2.png
  Tutorials/figs/SerialPortCommunication_I2CLoopback.png
Labels: documentation

#20 Fix missing link
  SUMMARY.md
Labels: invalid

#21 Add description of GitHub pages
  README.md
Labels: documentation, priority::low
