Repository ut-issl/s2e-documents, pull requests merged in 2022-05, with the labels that each got.

#30 Update to use VS2022
  General/HowToCompileWithVisualStudio.md
  General/figs/CMake_run.jpg
  General/figs/CMake_run.png
Labels: documentation, priority::high

#14 Fix How to integrate C2A
  Tutorials/HowToIntegrateC2A.md
  Tutorials/SampleCodes/C2A_Integration/C2A_src_user/Applications/AppRegistry.c
  Tutorials/SampleCodes/C2A_Integration/C2A_src_user/Applications/AppRegistry.h
  Tutorials/SampleCodes/C2A_Integration/C2A_src_user/Applications/CMakeLists.txt
  Tutorials/SampleCodes/C2A_Integration/C2A_src_user/Applications/DriverInstances/di_s2e_uart_test.c
  Tutorials/SampleCodes/C2A_Integration/C2A_src_user/Applications/DriverInstances/di_s2e_uart_test.h
  Tutorials/SampleCodes/C2A_Integration/C2A_src_user/Applications/app_headers.h
  Tutorials/SampleCodes/C2A_Integration/C2A_src_user/Applications/app_registry.c
  Tutorials/SampleCodes/C2A_Integration/C2A_src_user/Applications/app_registry.h
  Tutorials/SampleCodes/C2A_Integration/C2A_src_user/DriverInstances/rs422_dummy.c
  Tutorials/SampleCodes/C2A_Integration/C2A_src_user/DriverInstances/rs422_dummy.h
  Tutorials/SampleCodes/C2A_Integration/C2A_src_user/Settings/Modes/TaskLists/Composition/drivers_update.c
  Tutorials/SampleCodes/C2A_Integration/C2A_src_user/Settings/Modes/TaskLists/Elements/tl_elem_drivers_update.c
  Tutorials/SampleCodes/C2A_Integration/S2E_src/CMakeLists.txt
  Tutorials/SampleCodes/C2A_Integration/S2E_src/Simulation/Spacecraft/c2a_core_sample_components.cpp
  Tutorials/SampleCodes/C2A_Integration/S2E_src/Simulation/Spacecraft/c2a_core_sample_components.h
  Tutorials/SampleCodes/C2A_Integration/S2E_src/User_Components.cpp
  Tutorials/SampleCodes/C2A_Integration/S2E_src/User_Components.h
  Tutorials/SampleCodes/C2A_Integration/S2E_src/User_SimBase.ini
  Tutorials/figs/C2aCommunicationConfirmation.png
Labels: documentation, C2A

#32 Update HILS tutorial for v5.0.0
  Tutorials/HowToPerformI2cHilsTest.md
  Tutorials/HowToPerformUartHilsTest.md
Labels: documentation
